name: Publish gem to RubyGems.org

on:
    release:
        types: published
    workflow_dispatch:

permissions:
    id-token: write
    contents: write

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v4
            - name: Set up Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: 3.3.4
                  bundler-cache: true
            - name: Publish gem
              uses: rubygems/release-gem@v1
